'use client';
import { useState } from 'react';
import { TelemetryRow } from '@/lib/types';
import { calculateMotorHealth, getDeviationPct, BASELINE_POWER } from '@/lib/calculations';

interface MaintenanceHubProps {
  history: TelemetryRow[];
}

// Find the most anomalous row (highest power deviation)
function findAnomalyRow(history: TelemetryRow[]): TelemetryRow | null {
  if (!history.length) return null;
  return history.reduce((worst, row) =>
    Math.abs(getDeviationPct(row.power)) > Math.abs(getDeviationPct(worst.power)) ? row : worst
  );
}

function buildPrompt(row: TelemetryRow): string {
  const health = calculateMotorHealth(row.power);
  const dev = getDeviationPct(row.power);
  return `You are AeroSmart XAI, an industrial IoT maintenance AI. Generate a concise maintenance ticket based on this sensor anomaly data:

SENSOR READINGS:
- Voltage: ${row.voltage.toFixed(2)}V (baseline: 9.0V)
- Current: ${row.current.toFixed(3)}A (baseline: 0.5A)
- Power: ${row.power.toFixed(3)}W (baseline: ${BASELINE_POWER}W)
- Motor Health Index: ${health}%
- Power Deviation: ${dev >= 0 ? '+' : ''}${dev.toFixed(1)}% above baseline
- Gas PPM: ${row.gas} (threshold: 600 PPM)
- Temperature: ${row.temperature}°C
- Hazard Score: ${row.hazard_score}/100
- Fan Triggered: ${row.motor_active ? 'YES' : 'NO'}
- Timestamp: ${new Date(row.created_at).toLocaleString()}

Format the ticket exactly like this (keep the ━━━ separators, use CAPS for section headers):
TICKET #AES-[3 digit number]
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Priority    : [HIGH/MEDIUM/LOW based on severity]
Timestamp   : [formatted timestamp]
Status      : OPEN — Pending Technician

ISSUE
[One sentence describing the core problem]

SENSOR DATA
[List the key readings with labels and values]

DIAGNOSIS
[2-3 sentences explaining the root cause using the XAI data]

RECOMMENDED ACTIONS
[Numbered list of 4-5 concrete steps]

XAI CONTEXT (at time of trigger)
[Gas Factor, Temp Mult, Occ Penalty, Hazard Score formatted clearly]

Generated by AeroSmart XAI · Groq / Llama-3`;
}

export default function MaintenanceHub({ history }: MaintenanceHubProps) {
  const [ticketText, setTicketText] = useState(
    'Awaiting ticket generation.\nClick the button above to query the Groq API\nand generate a contextual maintenance report\nbased on the current anomaly data.'
  );
  const [loading, setLoading] = useState(false);
  const [success, setSuccess] = useState(false);

  const anomaly = findAnomalyRow(history);
  const latest  = history[0] ?? null;

  const displayRow = anomaly ?? latest;

  const motorHealth = displayRow ? calculateMotorHealth(displayRow.power) : 0;
  const deviation   = displayRow ? getDeviationPct(displayRow.power) : 0;
  const isAnomaly   = Math.abs(deviation) > 15;

  async function generateTicket() {
    if (!displayRow) return;
    setLoading(true);
    setSuccess(false);
    setTicketText('');

    try {
      const res = await fetch('/api/ticket', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: buildPrompt(displayRow) }),
      });

      if (!res.ok || !res.body) {
        const err = await res.json().catch(() => ({ error: 'API error' }));
        setTicketText(`Error: ${err.error ?? 'Unknown error'}`);
        setLoading(false);
        return;
      }

      // Stream typewriter from response
      const reader = res.body.getReader();
      const decoder = new TextDecoder();
      let done = false;

      while (!done) {
        const { value, done: doneReading } = await reader.read();
        done = doneReading;
        if (value) setTicketText(prev => prev + decoder.decode(value, { stream: true }));
      }

      setSuccess(true);
      setTimeout(() => setSuccess(false), 4000);
    } catch (e) {
      setTicketText(`Connection error: ${e instanceof Error ? e.message : 'Unknown'}`);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <div className="card" style={{ padding: 18 }}>
        <div className="section-title">
          <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="var(--amber)" strokeWidth="2">
            <circle cx="12" cy="12" r="3"/>
            <path d="M19.07 4.93a10 10 0 0 1 0 14.14M4.93 4.93a10 10 0 0 0 0 14.14"/>
          </svg>
          AI Maintenance Hub
        </div>

        {/* Anomaly Alert */}
        <div className="anomaly-alert">
          <svg className="anomaly-icon" viewBox="0 0 24 24" fill="none" stroke="var(--amber)" strokeWidth="2">
            <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/>
            <line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/>
          </svg>
          <div>
            <div className="anomaly-title">
              {isAnomaly ? 'Anomaly Detected — Motor Power Deviation' : 'Motor Status — Within Normal Range'}
            </div>
            <div className="anomaly-body">
              Drawing <strong>{displayRow?.current.toFixed(3) ?? '—'}A</strong> vs. baseline <strong>0.5A</strong>.{' '}
              Power deviation: <strong>{deviation >= 0 ? '+' : ''}{deviation.toFixed(1)}%</strong>.{' '}
              Voltage stable at {displayRow?.voltage.toFixed(2) ?? '—'}V —{' '}
              {isAnomaly ? 'battery ruled out as cause.' : 'no fault detected.'}
            </div>
          </div>
        </div>

        {/* Mini Stats */}
        <div className="mini-stats">
          <div className="mini-stat">
            <div className="mini-stat-label">Voltage</div>
            <div className="mini-stat-value">{displayRow?.voltage.toFixed(2) ?? '—'} V</div>
          </div>
          <div className="mini-stat">
            <div className="mini-stat-label">Current</div>
            <div className="mini-stat-value" style={{ color: isAnomaly ? 'var(--red)' : 'var(--green)' }}>
              {displayRow?.current.toFixed(3) ?? '—'} A
            </div>
          </div>
          <div className="mini-stat">
            <div className="mini-stat-label">Actual Power</div>
            <div className="mini-stat-value" style={{ color: isAnomaly ? 'var(--red)' : 'var(--green)' }}>
              {displayRow?.power.toFixed(3) ?? '—'} W
            </div>
          </div>
          <div className="mini-stat">
            <div className="mini-stat-label">Baseline</div>
            <div className="mini-stat-value" style={{ color: 'var(--green)' }}>{BASELINE_POWER} W</div>
          </div>
          <div className="mini-stat">
            <div className="mini-stat-label">Motor Health</div>
            <div className="mini-stat-value" style={{ color: motorHealth >= 85 ? 'var(--green)' : motorHealth >= 65 ? 'var(--amber)' : 'var(--red)' }}>
              {motorHealth}%
            </div>
          </div>
          <div className="mini-stat">
            <div className="mini-stat-label">Hazard Score</div>
            <div className="mini-stat-value">{displayRow?.hazard_score ?? '—'}/100</div>
          </div>
        </div>

        {/* Generate Button */}
        <div style={{ borderTop: '1px solid var(--border-lt)', paddingTop: 13, marginBottom: 11 }}>
          <button
            className={`btn-generate${success ? ' success' : ''}`}
            onClick={generateTicket}
            disabled={loading || !displayRow}
            id="gen-btn"
          >
            {loading ? (
              <>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ animation: 'spin 1s linear infinite' }}>
                  <path d="M21 12a9 9 0 1 1-6.219-8.56"/>
                </svg>
                Querying Groq API…
              </>
            ) : success ? (
              <>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <polyline points="20 6 9 17 4 12"/>
                </svg>
                Ticket Generated
              </>
            ) : (
              <>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                  <polyline points="14 2 14 8 20 8"/>
                  <line x1="12" y1="18" x2="12" y2="12"/>
                  <line x1="9" y1="15" x2="15" y2="15"/>
                </svg>
                Generate Maintenance Ticket
              </>
            )}
          </button>
        </div>

        <textarea
          className="ticket-output"
          readOnly
          id="ticket-area"
          value={ticketText}
          onChange={() => {}}
        />
        <div className="hub-note">Powered by Groq LLM API · Llama-3 reasoning core</div>
      </div>
    </div>
  );
}
