import { NextRequest, NextResponse } from 'next/server';

// Node.js runtime — groq-sdk and streaming work reliably here
export const runtime = 'nodejs';

const DEMO_TICKET = `TICKET #AES-001
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Priority    : HIGH
Timestamp   : ${new Date().toLocaleString()}
Status      : OPEN — Pending Technician

ISSUE
Exhaust Fan Motor Overcurrent Detected.

SENSOR DATA
  Voltage  = 9.1V (stable)
  Current  = 1.5A  (baseline: 0.5A)
  Power    = 13.65W (baseline: 4.5W)
  Motor Health = 84% (WARNING zone)
  Deviation: +87.5% above normal

DIAGNOSIS
High probability of mechanical friction on primary fan bearing
OR blocked ventilation duct causing backpressure. Battery voltage
stable at 9.1V — rules out power supply fault.

RECOMMENDED ACTIONS
  1. Shut down exhaust fan circuit immediately.
  2. Inspect fan blades for obstruction/debris.
  3. Apply industrial lubricant to motor bearing.
  4. Restart and monitor power signature for 10 minutes.
  5. If overcurrent persists, replace motor unit.

XAI CONTEXT (at time of trigger)
  Gas Factor   : 55.0
  Temp Mult    : 1.20x
  Occ Penalty  : 15 (occupied)
  Hazard Score : 78/100

Generated by AeroSmart XAI · Demo Mode`;

/** Stream a string character-by-character with a small delay */
function streamText(text: string, delayMs = 8): ReadableStream {
  return new ReadableStream({
    async start(controller) {
      const enc = new TextEncoder();
      for (const char of text) {
        controller.enqueue(enc.encode(char));
        await new Promise(r => setTimeout(r, delayMs));
      }
      controller.close();
    },
  });
}

export async function POST(req: NextRequest) {
  const groqKey = process.env.GROQ_API_KEY;

  // ── Demo fallback (no key set) ─────────────────────────────────────────
  if (!groqKey || groqKey === 'your_groq_api_key_here') {
    return new Response(streamText(DEMO_TICKET), {
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });
  }

  // ── Real Groq call via fetch (avoids SDK edge-runtime issues) ──────────
  let prompt: string;
  try {
    const body = await req.json();
    prompt = body.prompt;
  } catch {
    return NextResponse.json({ error: 'Invalid request body' }, { status: 400 });
  }

  try {
    const groqRes = await fetch('https://api.groq.com/openai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${groqKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'llama-3.1-8b-instant',
        messages: [{ role: 'user', content: prompt }],
        stream: true,
        max_tokens: 700,
        temperature: 0.3,
      }),
    });

    if (!groqRes.ok) {
      const errText = await groqRes.text();
      console.error('[Groq API error]', groqRes.status, errText);
      return NextResponse.json(
        { error: `Groq API returned ${groqRes.status}: ${errText.slice(0, 200)}` },
        { status: 502 }
      );
    }

    // Proxy Groq SSE stream → parse delta content → stream plain text to client
    const stream = new ReadableStream({
      async start(controller) {
        const enc = new TextEncoder();
        const reader = groqRes.body!.getReader();
        const dec = new TextDecoder();
        let buf = '';

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          buf += dec.decode(value, { stream: true });
          const lines = buf.split('\n');
          buf = lines.pop() ?? '';   // keep incomplete line in buffer

          for (const line of lines) {
            const trimmed = line.trim();
            if (!trimmed || trimmed === 'data: [DONE]') continue;
            if (!trimmed.startsWith('data: ')) continue;

            try {
              const json = JSON.parse(trimmed.slice(6));
              const text = json.choices?.[0]?.delta?.content ?? '';
              if (text) controller.enqueue(enc.encode(text));
            } catch {
              // malformed SSE line — skip
            }
          }
        }
        controller.close();
      },
    });

    return new Response(stream, {
      headers: { 'Content-Type': 'text/plain; charset=utf-8' },
    });

  } catch (err) {
    console.error('[ticket route error]', err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : 'Internal server error' },
      { status: 500 }
    );
  }
}
